apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
    dev.okteto.com/deployed-by: microservices-vote
  name: vote
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
        dev.okteto.com/deployed-by: microservices-vote
    spec:
      containers:
      - image: {{ .Values.image }}
        name: vote
        ports:
        - containerPort: 8080
          name: vote
